// Flat ESLint config (ESLint 9). Order matters — later entries win.
//
// Pinned to ESLint 9 deliberately: eslint-plugin-jsx-a11y (the signature ruleset for
// this accessibility-first project) has no ESLint 10 release yet, and eslint-plugin-astro
// 2.x requires ESLint 10 — the two can't coexist. We stay on the coherent ESLint 9 island
// (astro plugin 1.x) until jsx-a11y ships ESLint 10 support. See docs/adr/0005.
//
// `eslint-plugin-react` is intentionally omitted: under React 19's automatic JSX runtime
// its rules are largely redundant; jsx-a11y + react-hooks carry the real signal here.

import js from "@eslint/js";
import tseslint from "typescript-eslint";
import jsxA11y from "eslint-plugin-jsx-a11y";
import reactHooks from "eslint-plugin-react-hooks";
import astro from "eslint-plugin-astro";
import prettier from "eslint-config-prettier";
import globals from "globals";

export default [
  // 1. Never lint generated output or build artifacts. tokens.css is generated by
  //    Style Dictionary; global.css is hand-authored and intentionally kept.
  {
    ignores: [
      "dist/",
      ".astro/",
      "storybook-static/",
      "coverage/",
      "playwright-report/",
      "test-results/",
      ".lighthouseci/",
      "src/styles/tokens.css",
    ],
  },

  // 2. Browser + Node globals (islands run in the browser; config/test files in Node).
  { languageOptions: { globals: { ...globals.browser, ...globals.node } } },

  // 3. Core JS recommended.
  js.configs.recommended,

  // 4. TypeScript recommended — NON type-checked (no parserOptions.project). Type-aware
  //    linting is deferred (see ADR 0005); `astro check` covers type correctness.
  ...tseslint.configs.recommended,

  // 5. React Hooks rules (flat config) for the islands. The flat variants live under
  //    the `flat` namespace; the top-level `recommended-latest` is the legacy shape.
  reactHooks.configs.flat["recommended-latest"],

  // 6. jsx-a11y — the SIGNATURE accessibility ruleset — applied NATIVELY to the React
  //    island JSX/TSX, so the real `jsx-a11y/*` rules actually run on the interactive
  //    components. Scoped to {jsx,tsx}: jsx-a11y rules need a JSX AST, which the islands
  //    have. (.astro is parsed to a different AST by astro-eslint-parser, so native
  //    jsx-a11y rules don't apply there.)
  { ...jsxA11y.flatConfigs.recommended, files: ["**/*.{jsx,tsx}"] },

  // 7. Astro: parser + astro recommended rules for *.astro. Deliberately `flat/recommended`
  //    and NOT `flat/jsx-a11y-recommended`: the latter re-registers a `jsx-a11y` plugin
  //    under the same name as step 6 (ESLint forbids two configs redefining one plugin)
  //    AND its rules are astro-namespaced (`astro/jsx-a11y/*`), which only process .astro.
  //    Static a11y-linting of .astro templates is therefore left to the runtime axe suite
  //    (Playwright lints rendered output, which is stronger); revisit if templates grow.
  //    See docs/adr/0005.
  ...astro.configs["flat/recommended"],

  // 8. Prettier last — turn off stylistic rules; Prettier owns formatting.
  prettier,
];
