// style-dictionary.config.mjs
// Build via `pnpm tokens` → `style-dictionary build --config style-dictionary.config.mjs`.
//
// Runs under the Style Dictionary CLI. This file is ESM and imported by the CLI, so
// top-level register()/registerFormat() execute before the default export is consumed.
//
// OKLCH PRESERVATION: colors are authored as complete `oklch(...)` strings and we apply
// NO color transform, so they pass through verbatim. We intentionally do NOT use the
// `tokens-studio` transformGroup/preprocessor for this hand-written starter (several of its
// transforms reserialize color and would convert OKLCH → hex/rgb). sd-transforms is still
// installed + registered so a future Figma/Tokens Studio source can opt in (re-verify OKLCH
// output at that point).

import StyleDictionary from 'style-dictionary';
import { formattedVariables } from 'style-dictionary/utils';
import { register } from '@tokens-studio/sd-transforms';

register(StyleDictionary);

// Single-file tiered output: primitives → :root (raw values, no utilities);
// semantic → @theme (values as var(--primitive) refs, so Tailwind generates utilities
// AND keeps the indirection for runtime theming).
StyleDictionary.registerFormat({
  name: 'css/tiered',
  format: ({ dictionary, options }) => {
    const isPrimitive = (token) => token.filePath.includes('/primitive/');
    // usesDtcg must be forwarded so formattedVariables reads `$value` (DTCG), not `value`.
    const root = formattedVariables({
      format: 'css',
      dictionary: { ...dictionary, allTokens: dictionary.allTokens.filter(isPrimitive) },
      outputReferences: false,
      usesDtcg: options.usesDtcg,
    });
    const theme = formattedVariables({
      format: 'css',
      dictionary: { ...dictionary, allTokens: dictionary.allTokens.filter((t) => !isPrimitive(t)) },
      outputReferences: true,
      usesDtcg: options.usesDtcg,
    });
    return (
      '/* Generated by Style Dictionary — DO NOT EDIT. Edit tokens/*.json and run `pnpm tokens`. */\n\n' +
      `:root {\n${root}\n}\n\n` +
      `@theme {\n${theme}\n}\n`
    );
  },
});

export default {
  source: ['tokens/**/*.json'],
  platforms: {
    css: {
      // Explicit transforms only — NO color transform → OKLCH preserved.
      transforms: ['attribute/cti', 'name/kebab'],
      buildPath: 'src/styles/',
      files: [{ destination: 'tokens.css', format: 'css/tiered' }],
    },
  },
};
